-- 건의 사항 게시판 테이블 삭제
DROP TABLE SUGGESTIONBOARD;

-- 공지사항 게시판 테이블 삭제
DROP TABLE NOTICEBOARD;

-- 행사 테이블 삭제
DROP TABLE EVENTS;

-- 행사 타입 테이블 삭제
DROP TABLE EVENTSTYPE;

-- 파트타이머 근로계약서 테이블 삭제
DROP TABLE PARTTIMERCONTRACT;

-- 파트타이머 테이블 삭제
DROP TABLE PARTTIMER;

-- 은행구분 테이블 삭제
DROP TABLE BANKTYPE;

-- 관리자 테이블 삭제
DROP TABLE MANAGER;

-- 관리자 등급 테이블 삭제
DROP TABLE ADMINLEVEL;

-- 근로계약서 테이블 삭제 
DROP TABLE EMPLOYCONTRACT;

-- 은행 구분 테이블 생성 -- 
CREATE TABLE BANKTYPE(
    BTNO NUMBER(3) PRIMARY KEY,
    BTNAME VARCHAR2(30) NOT NULL
);

-- 관리자 등급 테이블 생성 -- 
CREATE TABLE ADMINLEVEL(
    ALLEVEL NUMBER(1) PRIMARY KEY,
    ALNAME VARCHAR2(20) NOT NULL
);

-- 관리자 테이블 생성 --
CREATE TABLE MANAGER(
    MNO NUMBER(8) PRIMARY KEY,
    MPW VARCHAR2(30) NOT NULL,
    MNAME VARCHAR2(20) NOT NULL,
    ALLEVEL NUMBER(1) REFERENCES ADMINLEVEL(ALLEVEL) NOT NULL
);

-- 행사 타입 테이블 생성
CREATE TABLE EVENTSTYPE(
    ETNO NUMBER(2) PRIMARY KEY,
    ETNAME VARCHAR2(20) NOT NULL
);

-- 행사 테이블 생성
CREATE TABLE EVENTS(
    EVNO VARCHAR2(9) PRIMARY KEY,
    EVTITLE VARCHAR2(150) NOT NULL,
    EVDETAIL VARCHAR2(4000),
    EVSTARTDATE DATE NOT NULL,
    ETNO NUMBER(2) REFERENCES EVENTSTYPE(ETNO) NOT NULL,
    MNO NUMBER(8) REFERENCES MANAGER(MNO) NOT NULL
);

-- 파트타이머 테이블 생성
CREATE TABLE PARTTIMER(
    PTID VARCHAR2(5) PRIMARY KEY,
    PTPW VARCHAR2(30) NOT NULL,
    PTEMPCONCHEK NUMBER(1) DEFAULT 0 NOT NULL
);

-- 파트타이머 근로계약서 테이블 생성
CREATE TABLE PARTTIMERCONTRACT(
    PTCONNO VARCHAR2(8) PRIMARY KEY,
    PTID VARCHAR2(5) REFERENCES PARTTIMER(PTID) NOT NULL,
    PTNAME VARCHAR2(10) NOT NULL,
    PTTEL VARCHAR2(13) NOT NULL,
    PTEMAIL VARCHAR2(50),
    PTADDRESS VARCHAR2(150),
    BTNO NUMBER(3) REFERENCES BANKTYPE(BTNO) NOT NULL,
    PTACCOUNTNO VARCHAR2(14) NOT NULL,
<<<<<<< HEAD
    EVNO VARCHAR2(9) REFERENCES EVENTS(EVNO),
    PTSTATUS NUMBER(1) DEFAULT 0 NOT NULL, 
    PTWORKTIME NUMBER(3),
=======
    EVNO NUMBER(9),
    PTSTATUS NUMBER(1) DEFAULT 0 NOT NULL, 
    PTWORKTIME NUMBER(2,1),
>>>>>>> ab135680e289d5c252352cc9bf3e3ad4612310eb
    PTHOURLYWAGE NUMBER(5),
    PTTOTALPAY NUMBER(6)
);

-- 건의 사항 게시판 테이블 생성
CREATE TABLE SUGGESTIONBOARD(
    SBNO NUMBER(8) PRIMARY KEY,
    PTID VARCHAR2(5) REFERENCES PARTTIMER(PTID) NOT NULL,
    MNO NUMBER(8),
    SBTITLE VARCHAR2(150) NOT NULL,
    SBCONTENT VARCHAR2(4000),
    SBFILENAME VARCHAR2(100),
    SBPW VARCHAR2(10),
    SBSTEP NUMBER(8) NOT NULL,
    SBINDENT NUMBER(8) NOT NULL,
    SBGROUP NUMBER(8) NOT NULL,
    SBHIT NUMBER(8) DEFAULT 0 NOT NULL,
    SBIP VARCHAR2(15) NOT NULL,
    SBRDATE TIMESTAMP DEFAULT SYSDATE NOT NULL
);

-- 공지사항 게시판 테이블 생성
CREATE TABLE NOTICEBOARD(
    NBNO NUMBER(8) PRIMARY KEY,
    MNO NUMBER(8) REFERENCES MANAGER(MNO) NOT NULL,
    NBTITLE VARCHAR2(150) NOT NULL,
    NBCONTENT VARCHAR2(4000) NOT NULL,
    NBFILENAME VARCHAR2(100),
    NBHIT NUMBER(8) DEFAULT 0 NOT NULL,
    NBRDATE TIMESTAMP DEFAULT SYSDATE NOT NULL
);

-- 근로계약서 테이블 생성 
CREATE TABLE EMPLOYCONTRACT(
    ECNO VARCHAR2(10) PRIMARY KEY,
    ECTITLE VARCHAR2(150) NOT NULL,
<<<<<<< HEAD
    ECCONTENT CLOB NOT NULL
);

COMMIT;
=======
    ECCONTENT VARCHAR2(4000) NOT NULL
);

COMMIT;













>>>>>>> ab135680e289d5c252352cc9bf3e3ad4612310eb
